DROP TABLE IF EXISTS "batches" CASCADE;
DROP TABLE IF EXISTS "bundles" CASCADE;
DROP TABLE IF EXISTS "charges" CASCADE;
DROP TABLE IF EXISTS "payment_logs" CASCADE;
DROP TABLE IF EXISTS "orders" CASCADE;
DROP TABLE IF EXISTS "customers" CASCADE;
DROP TABLE IF EXISTS "bundles_customers" CASCADE;
