// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: bundles.sql

package db

import (
	"context"
)

const addBundleToCustomer = `-- name: AddBundleToCustomer :exec
INSERT INTO bundles_customers (
  bundles_id, customers_id
) VALUES (
  $1, $2
)
`

type AddBundleToCustomerParams struct {
	BundlesID   int64 `json:"bundles_id"`
	CustomersID int64 `json:"customers_id"`
}

func (q *Queries) AddBundleToCustomer(ctx context.Context, arg AddBundleToCustomerParams) error {
	_, err := q.db.ExecContext(ctx, addBundleToCustomer, arg.BundlesID, arg.CustomersID)
	return err
}

const createBundle = `-- name: CreateBundle :one
INSERT INTO bundles (
  mrc, description
) VALUES (
  $1, $2
)
RETURNING id, mrc, description
`

type CreateBundleParams struct {
	Mrc         int32  `json:"mrc"`
	Description string `json:"description"`
}

func (q *Queries) CreateBundle(ctx context.Context, arg CreateBundleParams) (Bundle, error) {
	row := q.db.QueryRowContext(ctx, createBundle, arg.Mrc, arg.Description)
	var i Bundle
	err := row.Scan(&i.ID, &i.Mrc, &i.Description)
	return i, err
}

const deleteBundle = `-- name: DeleteBundle :exec
DELETE FROM bundles
WHERE id = $1
`

func (q *Queries) DeleteBundle(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteBundle, id)
	return err
}

const listBundlesByCustomerID = `-- name: ListBundlesByCustomerID :many
SELECT id, mrc, description, bundles_id, customers_id FROM bundles
JOIN bundles_customers ON bundles.id = bundles_customers.bundles_id
WHERE bundles_customers.customers_id = $1
ORDER BY bundles_customers.customers_id
`

type ListBundlesByCustomerIDRow struct {
	ID          int64  `json:"id"`
	Mrc         int32  `json:"mrc"`
	Description string `json:"description"`
	BundlesID   int64  `json:"bundles_id"`
	CustomersID int64  `json:"customers_id"`
}

func (q *Queries) ListBundlesByCustomerID(ctx context.Context, customersID int64) ([]ListBundlesByCustomerIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listBundlesByCustomerID, customersID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBundlesByCustomerIDRow{}
	for rows.Next() {
		var i ListBundlesByCustomerIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Mrc,
			&i.Description,
			&i.BundlesID,
			&i.CustomersID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
