// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: customers.sql

package db

import (
	"context"
)

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (
  customer
) VALUES (
  $1
)
RETURNING id, customer
`

func (q *Queries) CreateCustomer(ctx context.Context, customer string) (Customer, error) {
	row := q.db.QueryRowContext(ctx, createCustomer, customer)
	var i Customer
	err := row.Scan(&i.ID, &i.Customer)
	return i, err
}
