name: Deploy to production

on:
  push:
    branches: [ release ]

jobs:

  deploy:
    name: Build image
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build, tag, and push image to Amazon ECR
      env:
        REPOSITORY: nadersameh8/billing
        IMAGE_TAG: ${{ github.sha }}

      run: |
        docker build -t $REPOSITORY:$IMAGE_TAG -t $REPOSITORY:latest .
        docker push -a $REPOSITORY